export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_WITH_QUANTITY = "REMOVE_ITEM_WITH_QUANTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
